### ISSUE TITLE
Hi,  i want to svn  operation remote and do not svn checkout in my local disk, what should i do ?

### ISSUE THREAD

**Issue by joostshao** [aholmes/php-svn#3]
Hi,  i want to svn  operation remote and do not svn checkout in my local disk, what should i do ?

the extension is simple,  there should be a api like this: 

svn_add($repo_url, $fileOrFolder, $user, $password, $revere, $force);

i know it is not easy.

**Comment by aholmes** [comment]
You'll have to check out the repository in order to make any changes. SVN does let you check out a portion of a repository if you'd like to avoid checking out the whole thing.

Try asking your question on stackoverflow.com. You will get more responses there than here. Feel free to post the link to your question, and I can take a look.

-----Original Message-----
